# Generated by Django 3.2.5 on 2021-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_topic', models.CharField(max_length=200)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
